### ISSUE TITLE
TCon slime filtering?

### ISSUE THREAD

**Issue by scribbler957** [zlainsama/PeacefulSurface#11]
Is there a way to filter for specific mods to allow TCon slimes to spawn? Actually, I'd like to get slimes back in the swamps too.

**Comment by zlainsama** [comment]
You will need the name of that mob. (like Slime, Witch, Enderman, etc.)
By default, normal Slime spawning should be untouched.
But due to my mistake, the old default settings treat Slime same as other hostile mobs.
If you are using an old version or an old rule file, you need to update the regex for mob filtering, so that normal Slime spawning will not be affected by the rule.

Corresponding settings should be like this for it to let normal Slime do their normal spawning:
```json
{
    "InvertedMobFilter": false,
    "mobFilter": "(\\bSlime\\b)"
}
```

**Comment by charlesbevans** [comment]
The default file has 
`"mobFilter": "(\bSlime\b)"`

**Comment by charlesbevans** [comment]
It's not working for me. I know EU2 has an issue with slime chunks, I'm going to look around for other mod interactions to see why I can't get Blue Slime to spawn. I'll let you know if I find anything.
